name: Flutter Web Deploy

on:
  push:
    branches: [ main ]  # Triggers on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      # Get dependencies and build web
      - name: Build Flutter Web
        run: |
          cd flutter_portfolio
          flutter pub get
          flutter build web --release
      
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region  # e.g., us-east-1
      
      # Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync build/web/ s3://your-bucket-name --delete
      
      # Optional: Invalidate CloudFront cache if using CDN
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"