name: Flutter Web Deploy

on:
  push:
    branches: [ main ]  # Triggers on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      
      # Enable web and get dependencies
      - name: Build Flutter Web
        run: |
          cd flutter_portfolio
          flutter config --enable-web
          flutter pub get
          flutter build web --release
          ls -la build/web  # Debug: verify build contents
      
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # Deploy to S3
      - name: Deploy to S3
        run: |
          cd flutter_portfolio
          aws s3 sync build/web/ s3://portfolio.codewithrk.xyz --delete
      
      # Optional: Invalidate CloudFront cache if using CDN
      - name: Invalidate CloudFront
        if: success()  # Only run if previous steps succeeded
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"